# Creating a mutual fund plan with python

A mutual fund plan is created by selecting the stocks where an investor can benfit in the long term. Here is the process we can follow to create a mutual fund plan:
STEP 1: Gather historical data, such as closing price and growth tends over time.
STEP 2: calculate key metrics like return on investment(ROI) and volatility(risk) to understand how each stock has performed historically.
STEP 3: choose stocks that have high ROI and low volatility to ensure a balance between risk and reward.
STEP 4: calculate the future value of monthly investment based on the expected ROI of the selected stocks.

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objs as go
import plotly.express as px

In [36]:
""" 
The plotly.graph_objs as go:
1.)gives fine grained control for building complex and highly customized visualizations.
2.)you build charts by manually defining data and layout.

The plotly.express as px:
1.)High level interface;great for quick and simple plots.
2.)Automatically handles axes, legends, coloring, etc.
"""

' \nThe plotly.graph_objs as go:\n1.)gives fine grained control for building complex and highly customized visualizations.\n2.)you build charts by manually defining data and layout.\n\nThe plotly.express as px:\n1.)High level interface;great for quick and simple plots.\n2.)Automatically handles axes, legends, coloring, etc.\n'

In [85]:
data = pd.read_csv('nifty.csv')

In [86]:
data

,Date,RELIANCE.NS,HDFCBANK.NS,ICICIBANK.NS,INFY.NS,TCS.NS,KOTAKBANK.NS,HINDUNILVR.NS,ITC.NS,LT.NS,...,HEROMOTOCO.NS,DRREDDY.NS,SHREECEM.NS,BRITANNIA.NS,UPL.NS,EICHERMOT.NS,SBILIFE.NS,ADANIPORTS.NS,BAJAJ-AUTO.NS,HINDALCO.NS
0,2024-08-20 00:00:00+05:30,2991.899902,1637.699951,1179.449951,1872.199951,4523.299805,1805.650024,2751.050049,498.799988,3572.699951,...,5244.399902,6965.350098,24730.550781,5765.799805,566.150024,4883.250000,1761.300049,1492.550049,9779.700195,672.900024
1,2024-08-21 00:00:00+05:30,2997.350098,1625.800049,1174.849976,1872.699951,4551.500000,1812.949951,2791.199951,505.399994,3596.050049,...,5284.700195,7062.450195,24808.050781,5837.350098,568.299988,4913.549805,1800.599976,1503.500000,9852.000000,685.599976
2,2024-08-22 00:00:00+05:30,2996.250000,1631.300049,1191.099976,1880.250000,4502.000000,1821.500000,2792.800049,504.549988,3606.500000,...,5329.950195,6969.049805,25012.400391,5836.799805,579.150024,4933.549805,1795.250000,1492.300049,9914.200195,685.549988
3,2024-08-23 00:00:00+05:30,2999.949951,1625.050049,1203.500000,1862.099976,4463.899902,1818.000000,2815.600098,505.799988,3598.550049,...,5384.899902,6954.500000,24706.050781,5792.649902,573.700012,4898.100098,1789.300049,1491.300049,10406.450195,685.099976
4,2024-08-26 00:00:00+05:30,3025.199951,1639.949951,1213.300049,1876.150024,4502.450195,1812.500000,2821.149902,505.700012,3641.899902,...,5343.750000,6943.299805,24906.449219,5796.950195,577.450012,4875.200195,1796.250000,1482.550049,10432.549805,711.849976
5,2024-08-27 00:00:00+05:30,3000.899902,1637.750000,1226.349976,1900.099976,4497.149902,1803.349976,2766.899902,500.600006,3702.699951,...,5356.549805,6962.950195,24813.199219,5764.299805,582.950012,4868.850098,1838.949951,1478.349976,10501.599609,703.500000
6,2024-08-28 00:00:00+05:30,2996.600098,1637.099976,1223.849976,1939.099976,4506.049805,1791.300049,2764.350098,497.299988,3689.050049,...,5311.399902,6999.299805,24692.199219,5703.350098,578.049988,4946.850098,1843.699951,1469.800049,10656.750000,705.049988
7,2024-08-29 00:00:00+05:30,3041.850098,1638.550049,1221.900024,1933.349976,4511.799805,1777.250000,2785.250000,505.100006,3683.449951,...,5374.500000,6931.149902,24821.349609,5831.399902,577.799988,4915.899902,1843.699951,1476.050049,10807.849609,700.500000
8,2024-08-30 00:00:00+05:30,3019.250000,1636.900024,1229.199951,1943.699951,4553.750000,1780.800049,2778.000000,501.899994,3704.649902,...,5455.399902,7031.350098,25482.000000,5855.250000,598.349976,4960.500000,1850.300049,1481.900024,10891.549805,701.349976
9,2024-09-02 00:00:00+05:30,3032.500000,1626.949951,1229.949951,1964.500000,4521.049805,1780.250000,2789.050049,510.049988,3683.100098,...,5578.200195,6872.149902,25427.300781,5922.149902,599.500000,4911.950195,1888.750000,1494.500000,11126.099609,683.900024
10,2024-09-03 00:00:00+05:30,3018.250000,1637.349976,1247.699951,1941.250000,4512.350098,1783.800049,2794.300049,509.399994,3690.149902,...,5646.500000,6853.850098,25507.599609,5916.049805,602.200012,4865.799805,1928.650024,1479.550049,11043.650391,678.900024
11,2024-09-04 00:00:00+05:30,3029.100098,1641.800049,1236.349976,1922.449951,4479.250000,1783.800049,2841.250000,506.350006,3650.800049,...,5683.750000,6787.200195,25770.750000,5926.549805,607.849976,4833.549805,1912.199951,1472.099976,10963.700195,666.799988
12,2024-09-05 00:00:00+05:30,2985.949951,1645.449951,1235.949951,1933.150024,4475.950195,1777.949951,2838.449951,511.200012,3624.149902,...,5734.200195,6695.750000,25662.250000,5850.000000,618.700012,4800.100098,1907.849976,1465.550049,10855.750000,669.950012
13,2024-09-06 00:00:00+05:30,2929.649902,1636.949951,1208.150024,1901.849976,4456.750000,1764.150024,2838.949951,501.700012,3574.750000,...,5743.750000,6667.149902,25610.449219,5843.549805,609.799988,4752.500000,1896.300049,1442.400024,10830.099609,667.099976
14,2024-09-09 00:00:00+05:30,2924.899902,1646.500000,1235.000000,1894.650024,4449.549805,1790.150024,2921.800049,511.750000,3578.300049,...,5745.299805,6655.899902,25798.599609,5939.450195,604.400024,4747.350098,1901.750000,1435.900024,10847.599609,658.549988
15,2024-09-10 00:00:00+05:30,2923.050049,1650.349976,1237.300049,1912.300049,4507.850098,1791.599976,2898.600098,513.599976,3596.149902,...,5669.700195,6650.399902,25725.150391,5969.899902,619.200012,4737.200195,1853.449951,1453.400024,10987.750000,659.500000
16,2024-09-11 00:00:00+05:30,2903.000000,1643.900024,1236.349976,1910.150024,4479.350098,1789.250000,2904.149902,514.349976,3536.949951,...,5654.450195,6612.500000,25614.099609,6008.649902,611.000000,4726.649902,1859.150024,1430.599976,11420.750000,647.700012
17,2024-09-12 00:00:00+05:30,2959.600098,1666.599976,1252.150024,1950.449951,4517.700195,1827.449951,2956.399902,519.500000,3622.000000,...,5803.149902,6683.850098,26019.650391,6109.250000,614.849976,4875.000000,1875.949951,1472.599976,11723.500000,676.200012
18,2024-09-13 00:00:00+05:30,2945.250000,1665.949951,1250.349976,1944.099976,4522.600098,1820.349976,2932.949951,513.849976,3613.000000,...,5795.799805,6660.700195,25883.099609,6133.100098,611.400024,4858.299805,1846.500000,1452.099976,11737.150391,673.250000
19,2024-09-16 00:00:00+05:30,2942.699951,1670.949951,1262.849976,1950.250000,4513.250000,1831.300049,2867.100098,511.100006,3662.250000,...,5779.450195,6647.100098,25619.400391,6063.000000,613.799988,4899.200195,1821.250000,1440.699951,11688.349609,685.150024
20,2024-09-17 00:00:00+05:30,2944.600098,1668.800049,1268.099976,1952.550049,4505.649902,1846.650024,2873.500000,507.750000,3695.199951,...,5961.200195,6631.649902,25437.099609,6111.049805,610.650024,4850.200195,1819.150024,1426.599976,11950.299805,683.000000
21,2024-09-18 00:00:00+05:30,2926.899902,1694.800049,1288.349976,1892.150024,4346.149902,1839.699951,2875.850098,507.350006,3730.449951,...,5964.750000,6567.799805,25076.650391,6123.250000,605.099976,4850.350098,1842.449951,1428.800049,11764.650391,685.250000
22,2024-09-19 00:00:00+05:30,2939.350098,1708.500000,1292.000000,1894.199951,4296.149902,1871.949951,2911.750000,508.250000,3683.699951,...,6006.049805,6502.549805,24931.699219,6134.500000,594.799988,4864.899902,1840.949951,1408.199951,11868.000000,684.200012
23,2024-09-20 00:00:00+05:30,2971.850098,1741.199951,1338.449951,1905.750000,4284.899902,1904.500000,2977.600098,514.400024,3793.899902,...,6013.250000,6551.149902,25141.699219,6210.549805,587.099976,4963.149902,1870.250000,1438.699951,11941.700195,694.400024

In [88]:
data.head()

,Date,RELIANCE.NS,HDFCBANK.NS,ICICIBANK.NS,INFY.NS,TCS.NS,KOTAKBANK.NS,HINDUNILVR.NS,ITC.NS,LT.NS,...,HEROMOTOCO.NS,DRREDDY.NS,SHREECEM.NS,BRITANNIA.NS,UPL.NS,EICHERMOT.NS,SBILIFE.NS,ADANIPORTS.NS,BAJAJ-AUTO.NS,HINDALCO.NS
0,2024-08-20 00:00:00+05:30,2991.899902,1637.699951,1179.449951,1872.199951,4523.299805,1805.650024,2751.050049,498.799988,3572.699951,...,5244.399902,6965.350098,24730.550781,5765.799805,566.150024,4883.250000,1761.300049,1492.550049,9779.700195,672.900024
1,2024-08-21 00:00:00+05:30,2997.350098,1625.800049,1174.849976,1872.699951,4551.500000,1812.949951,2791.199951,505.399994,3596.050049,...,5284.700195,7062.450195,24808.050781,5837.350098,568.299988,4913.549805,1800.599976,1503.500000,9852.000000,685.599976
2,2024-08-22 00:00:00+05:30,2996.250000,1631.300049,1191.099976,1880.250000,4502.000000,1821.500000,2792.800049,504.549988,3606.500000,...,5329.950195,6969.049805,25012.400391,5836.799805,579.150024,4933.549805,1795.250000,1492.300049,9914.200195,685.549988
3,2024-08-23 00:00:00+05:30,2999.949951,1625.050049,1203.500000,1862.099976,4463.899902,1818.000000,2815.600098,505.799988,3598.550049,...,5384.899902,6954.500000,24706.050781,5792.649902,573.700012,4898.100098,1789.300049,1491.300049,10406.450195,685.099976
4,2024-08-26 00:00:00+05:30,3025.199951,1639.949951,1213.300049,1876.150024,4502.450195,1812.500000,2821.149902,505.700012,3641.899902,...,5343.750000,6943.299805,24906.449219,5796.950195,577.450012,4875.200195,1796.250000,1482.550049,10432.549805,711.849976

In [89]:
data['Date'] = pd.to_datetime(data['Date'])

In [90]:
data.isnull().sum()

Date              0
RELIANCE.NS       0
HDFCBANK.NS       0
ICICIBANK.NS      0
INFY.NS           0
TCS.NS            0
KOTAKBANK.NS      0
HINDUNILVR.NS     0
ITC.NS            0
LT.NS             0
SBIN.NS           0
BAJFINANCE.NS     0
BHARTIARTL.NS     0
HCLTECH.NS        0
ASIANPAINT.NS     0
AXISBANK.NS       0
DMART.NS          0
MARUTI.NS         0
ULTRACEMCO.NS     0
HDFC.NS          24
TITAN.NS          0
SUNPHARMA.NS      0
M&M.NS            0
NESTLEIND.NS      0
WIPRO.NS          0
ADANIGREEN.NS     0
TATASTEEL.NS      0
JSWSTEEL.NS       0
POWERGRID.NS      0
ONGC.NS           0
NTPC.NS           0
COALINDIA.NS      0
BPCL.NS           0
IOC.NS            0
TECHM.NS          0
INDUSINDBK.NS     0
DIVISLAB.NS       0
GRASIM.NS         0
CIPLA.NS          0
BAJAJFINSV.NS     0
TATAMOTORS.NS     0
HEROMOTOCO.NS     0
DRREDDY.NS        0
SHREECEM.NS       0
BRITANNIA.NS      0
UPL.NS            0
EICHERMOT.NS      0
SBILIFE.NS        0
ADANIPORTS.NS     0
BAJAJ-AUTO.NS     0
HINDALCO.NS       0
dtype: int64

In [91]:
# Here the HDFC.NS has no values so we dropped that column
data.drop(columns=['HDFC.NS'], inplace= True)

In [ ]:
"""
1.)looping through each company column in the df, skipping the first column(assumed to be date)
2.)the whole block adds one line trace per company
3.)next block updates the layoutof the figure
"""

In [92]:
fig = go.Figure()

for company in data.columns[1:]:
    fig.add_trace(go.Scatter(x=data['Date'], y=data[company],
                             mode='lines',
                             name=company,
                             opacity=0.5))

fig.update_layout(
    title='Stock Price Trends of All Indian Companies',
    xaxis_title='Date',
    yaxis_title='Closing Price (INR)',
    xaxis=dict(tickangle=45), 
    legend=dict(
        x=1.05,
        y=1,
        traceorder="normal",
        font=dict(size=10),
        orientation="v"
    ),
    margin=dict(l=0, r=0, t=30, b=0),  
    hovermode='x',
    template='plotly_white'
)

fig.show()

In [93]:
#Now look at the companies with the highest risks for investing
#we pulled the standard deviation of the comapnies and we arranges in desc an dthe top are the high risk to invest

all_companies = data.columns[1:]

volatility_all_companies = data[all_companies].std()

volatility_all_companies.sort_values(ascending=False).head(10)

BAJAJ-AUTO.NS    659.810841
SHREECEM.NS      429.919834
BAJFINANCE.NS    306.658594
DIVISLAB.NS      247.674895
HEROMOTOCO.NS    247.092728
DRREDDY.NS       175.124908
ULTRACEMCO.NS    172.673053
DMART.NS         155.593701
BRITANNIA.NS     144.164343
MARUTI.NS        109.587342
dtype: float64

In [94]:
#Now we look for the highest growth rate for investing

growth_all_companies = data[all_companies].pct_change() * 100

average_growth_all_companies = growth_all_companies.mean()

average_growth_all_companies.sort_values(ascending=False).head(10)

BAJAJ-AUTO.NS    0.883421
BAJAJFINSV.NS    0.791730
BHARTIARTL.NS    0.735219
DIVISLAB.NS      0.634851
HEROMOTOCO.NS    0.602192
ICICIBANK.NS     0.557742
BAJFINANCE.NS    0.536819
TITAN.NS         0.393800
HINDUNILVR.NS    0.351634
BRITANNIA.NS     0.327747
dtype: float64

In [50]:
#Companies with the highest return on investment

initial_price_all = df[all_companies].iloc[0]
final_price_all = df[all_companies].iloc[-1]
roi_all_companies = ((final_price_all - initial_price_all)/ initial_price_all)*100
roi_all_companies.sort_values(ascending=False).head(10)

BAJAJ-AUTO.NS    22.107017
BAJAJFINSV.NS    19.642973
BHARTIARTL.NS    18.120965
DIVISLAB.NS      15.404976
HEROMOTOCO.NS    14.660402
ICICIBANK.NS     13.480860
BAJFINANCE.NS    12.797149
TITAN.NS          9.275089
HINDUNILVR.NS     8.235039
BRITANNIA.NS      7.713587
dtype: float64

Creating a mutual fund paln based on high ROI and low risk. The goal is to find compaines that offer a high ROI but with low volatility to minimize risk.
Here are the steps we can follow:
Step 1: Define ROI and volatility threshold - We set threshold for ROI and volatility to select companies that provide good returns with lower risk
Step 2: Rank companies by ROI and volatility
Step 3: Assign investment ratios - Allocate more investment to companies with higher ROI and lower volatility.

In [95]:
#Lets start by defining threshold and selecting companies that meet the criteria

roi_threshold = roi_all_companies.median()
volatility_threshold = volatility_all_companies.median()

selected_companies = roi_all_companies[(roi_all_companies > roi_threshold) & (volatility_all_companies < volatility_threshold)]

selected_companies.sort_values(ascending=False)

ICICIBANK.NS     13.480860
INDUSINDBK.NS     7.159914
JSWSTEEL.NS       7.021748
AXISBANK.NS       6.592466
HDFCBANK.NS       6.319839
SUNPHARMA.NS      5.627425
KOTAKBANK.NS      5.474481
CIPLA.NS          4.850117
NTPC.NS           4.356926
dtype: float64

In [96]:
#to balance the investment between these comapnies, we can use an inverse volatility ratio fpr allocation. compaines with lower volatility will get a higher weight.

selected_volatility = volatility_all_companies[selected_comapnies.index]
inverse_volatility = 1 / selected_volatility

investment_ratios = (inverse_volatility/inverse_volatility.sum())*100
investment_ratios.sort_values(ascending=False).head(10)

NTPC.NS          28.076767
JSWSTEEL.NS      15.998503
AXISBANK.NS       9.223133
HDFCBANK.NS       8.933035
CIPLA.NS          8.478347
KOTAKBANK.NS      7.664235
INDUSINDBK.NS     7.443153
SUNPHARMA.NS      7.255261
ICICIBANK.NS      6.927566
dtype: float64

In [ ]:
"""
Analyzing the mutual fund plan:

we created a mutual fund plan for long term investments.
now lets analyze and compare our mutual fund plan by comparing it with the high performing companies in the stock market.
lets start by comparing the risk in our mutual fund with the risk in the high growth companies.
"""

In [97]:
top_growth_companies = average_growth_all_companies.sort_values(ascending=False).head(10)
risk_growth_rate_companies = volatility_all_companies[top_growth_companies.index]
risk_mutual_fund_companies = volatility_all_companies[selected_companies.index]

fig = go.Figure()

fig.add_trace(go.Bar(
    x=risk_mutual_fund_companies,
    y=risk_mutual_fund_companies.index,
    orientation = 'h', #horizontal bar
    name="mutual fund companies",
    marker=dict(color='blue')

))

fig.add_trace(go.Bar(
    x=risk_growth_rate_companies,
    y=risk_growth_rate_comapnies.index,
    orientation='h',
    name='growth rate comapnies',
    marker=dict(color='green'),
    opacity = 0.6
))

fig.update_layout(
    title='Risk Comparision: Mutual Funds Vs Growth Rate Companies',
    xaxis_title='volatility(SD)',
    yaxis_title='Companies',
    barmode='overlay',
    legend=dict(title='company type'),
    template='plotly_white'
)

fig.show()

In [ ]:
#Lets compare the ROI of the both groups as well

In [98]:
expected_roi_mutual_fund = roi_all_companies[selected_companies.index]

expected_roi_growth_companies = roi_all_companies[top_growth_companies.index]

fig = go.Figure()

fig.add_trace(go.Bar(
    y=expected_roi_mutual_fund.index,
    x=expected_roi_mutual_fund,
    orientation='h',  
    name='Mutual Fund Companies',
    marker=dict(color='blue')
))

fig.add_trace(go.Bar(
    y=expected_roi_growth_companies.index,
    x=expected_roi_growth_companies,
    orientation='h',  
    name='Growth Rate Companies',
    marker=dict(color='green'),
    opacity=0.7
))

fig.update_layout(
    title='Expected ROI Comparison: Mutual Fund vs Growth Rate Companies',
    xaxis_title='Expected ROI (%)',
    yaxis_title='Companies',
    barmode='overlay',  
    legend=dict(title='Company Type'),
    template='plotly_white'
)

fig.show()

In [ ]:
#calculating expected returns

In [102]:
monthly_investment = 5000  # Monthly investment in INR
years = [1, 3, 5, 10]  # Investment periods (in years)
n = 12  # Number of times interest is compounded per year (monthly)

avg_roi = expected_roi_mutual_fund.mean() / 100  # Convert to decimal

def future_value(P, r, n, t):
    return P * (((1 + r/n)**(n*t) - 1) / (r/n)) * (1 + r/n)

future_values = [future_value(monthly_investment, avg_roi, n, t) for t in years]

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=[str(year) + " year" for year in years],
    y=future_values,
    mode='lines+markers',
    line=dict(color='blue'),
    marker=dict(size=8),
    name='Future Value'
))

fig.update_layout(
    title="Expected Value of Investments of ₹ 5000 Per Month (Mutual Funds)",
    xaxis_title="Investment Period",
    yaxis_title="Future Value (INR)",
    xaxis=dict(showgrid=True, gridcolor='lightgrey'),
    yaxis=dict(showgrid=True, gridcolor='lightgrey'),
    template="plotly_white",
    hovermode='x'
)

fig.show()

So, this is how a mutual fund plan is designed by investment companies for long-term investors. Mutual funds are investment plans that pool money from multiple investors to purchase a diversified portfolio of stocks, bonds, and other securities, managed by professional fund managers.